from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1309, 701)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel { background-color : rgb(211,211,211);border-radius: 10px;}")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(1)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.prevButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.prevButton_2.setObjectName("prevButton_2")
        self.horizontalLayout.addWidget(self.prevButton_2)
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.nextButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.nextButton_3.setObjectName("nextButton_3")
        self.horizontalLayout.addWidget(self.nextButton_3)
        self.horizontalSlider = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(350, 16777215))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "No music"))
        self.prevButton_2.setText(_translate("MainWindow", "Prev"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.nextButton_3.setText(_translate("MainWindow", "Next"))

